### PR TITLE
Fix compilation of busybox with x86 & MIPS platforms

### PR DESCRIPTION
**Pull request by ukanth**
I've used your patches to build busybox (as part of AFWall+) and fixed issues with x86 and mips platforms. Kindly let me know if you need any information 

You can see the builds from https://travis-ci.org/ukanth/afwall with these patches
Source
https://github.com/ukanth/afwall/tree/beta/external/dist

### CODE REVIEW

**Comment by osm0sis** [comment]
Hi! Thanks for the submission!

Can you make it match my other patches? They follow the "e-mail" diff format, and it can be done by first squashing your changes into 1 commit, then `git format-patch HEAD~1`; then please rename the patch as 017-f-missing_syscalls-semctl.patch (and bump the current 017-f- up to 017-g-) since that seems to be where it belongs. 👍 

Please also make the commit message explain the x86 and mips issues further, I'm guessing you're trying to resolve my "If building other than arm, exclude 017* and 025* and disable ipcrm/ipcs + syslogd/logread accordingly" caveat from osm0sis-full.config, in which case please update that note accordingly as well. 😃

**Comment by ukanth** [comment]
Thanks @osm0sis , I'm not good at creating patches(never done it before), I followed your steps and submitted again. Let me know If it's correct or I will resubmit :)

**Comment by osm0sis** [comment]
That looks much better! Nice work!

Can you just rename the f and g patches to switch those letter? Your syscalls patch should definitely come before the syslogd one.

Then it should be good to go!

**Comment by osm0sis** [comment]
Actually it looks like you didn't follow my instructions completely and just cut and paste your diffs in..?

If it's done correctly both files should be listed at the top. Seems like you didn't properly squash your commits first.

Also, does this fix ipcrm+ipcs?

**Comment by ukanth** [comment]
Yes. let me close this and do a clean one from scratch .

**Comment by ukanth** [comment]
Sorry, I was not able to make it work with your steps. Could you give me step by step guide ?

Yes, it does work with osm0sis-full.config 

Thanks,
[01_missing_interface_x86_patch.txt](https://github.com/osm0sis/android-busybox-ndk/files/819119/01_missing_interface_x86_patch.txt)

**Comment by osm0sis** [comment]
Leave your commits as they are, I'll write a properly formated patch based on what you've got here..

Thanks for finding a solution to the x86 + mips issues. :slightly_smiling_face:

For future reference all you needed to do was rebase and squash your changes into a single commit then use the command I posted.

**Comment by ukanth** [comment]
These are the steps I followed, correct me If I'm wrong
1. copy my patch to patches folder and rename it to 017-f-missing_syscalls-semctl.patch
2. git add 017-f-missing_syscalls-semctl.patch
3. git commit -m "<comment>" 
4. git format-patch HEAD~1

this is where the confusion. It created 0001-....patch file.

5. I renamed that file to 017-f-missing_syscalls-semctl.patch

but If I try to use the above one, build failed

**Comment by osm0sis** [comment]
You would make the changes to the busybox git repo, add them in one commit, then use the format-patch command to make the patch to be added to this repo.

**Pull request closed without merging**
