### PR TITLE
Nitpick: cd

### PR DESCRIPTION
**Pull request by equwal**
Basic edit.

P.S. The bit.do shortlinks don't work anymore. There's some in here and in the releases repo.

### CODE REVIEW

**Comment by osm0sis** [comment]
Thanks! Yeah I need to find a new custom short links provider, bit.do doesn't seem like it's coming back.. 😕

**Comment by equwal** [comment]
For documentation, why not just not use shortlink services? Seems like it would just cause unnecessary bitrot.

Since I've been messing with my phone, I've been interested in this question. I find that the "qrencode" and "qr" programs are nice for passing a link from the computer to the phone. Also passwords too
```
xclip -o | qr
xclip -o | qrencode -o qrcode.png
zbarimg qrconde.png
pass my/pasword | qr
```
If you have your own web server, you can just manually upload HTTP 300 response files that have been edited. This is the best solution.
I'd like to be able to run such a service and let people I know just point whatever domain they want at my service. Suggestions welcome.
HDA.me had a "short" and "long" link shortening option, which I think was a nice feature. So you could have ultra-short domains that don't last very long, or longer ones that will live the lifetime of the service.

I know that https://t.ly works currently. It has a nice short domain name too.

I used to use this on my old site whenever I restructured the pages. Just make one for every old page URL and throw it in the `redirects/` folder of my static content generator. I guess it isn't "correct" since it isn't a proper 300 "page moved" response, but it works.
```
;;; static content generator metadata
;;; filename: old-link-location.html
<head>
<meta http-equiv="refresh" content="0; url=https://target-domain-place.com/etc" />
</head>
<p><a href="https://target-domain-place.com/etc">Redirecting you!</a></p>
```

**Comment by equwal** [comment]
For a bloated modern solution, I found polr. You can even just pick your own shortlink.

http://demo.polr.me/cunt

https://www.polrproject.org/

**Comment by osm0sis** [comment]
Oh, just for your knowledge by the way, re: not using short links to avoid bit rot, there's a hard 1000 char limit in the Magisk update.json changelog.md parsing, so I have to try and be conservative with the info I include and have tried to save some bytes using short links. 👍

Edit: There, did what I could within the 1000 char limit for all my module README.md files while using as few short links as possible, and updated the remaining ones to a working provider: https://is.gd 🙂

**Pull request merged**
